expRemoveAll();
expAdd ("gMotorVars[0].Flag_enableSys", getDecimal());
expAdd ("gMotorVars[0].Flag_Run_Identify", getDecimal());
expAdd ("gMotorVars[0].Flag_enableOffsetcalc", getDecimal());
expAdd ("gMotorVars[0].Flag_enableAlignment", getDecimal());
expAdd ("gMotorVars[0].IqRef_A", getQValue(24));
expAdd ("gMotorVars[0].Speed_krpm", getQValue(24));
expAdd ("gMotorVars[0].Vd", getQValue(24));
expAdd ("gMotorVars[0].Vq", getQValue(24));
expAdd ("gMotorVars[0].Vs", getQValue(24));
expAdd ("gMotorVars[0].Id_A", getQValue(24));
expAdd ("gMotorVars[0].Iq_A", getQValue(24));
expAdd ("gMotorVars[0].Is_A", getQValue(24));
expAdd ("gMotorVars[0].VdcBus_kV", getQValue(24));
expAdd ("pid[0]", getQValue(24));
expAdd ("gPwmData[0]", getQValue(24));
expAdd ("gDrvSpi8305Vars[0]");

expAdd ("gMotorVars[1].Flag_Run_Identify", getDecimal());
expAdd ("gMotorVars[1].Flag_enableOffsetcalc", getDecimal());
expAdd ("gMotorVars[1].Flag_enableAlignment", getDecimal());
expAdd ("gMotorVars[0].IqRef_A", getQValue(24));
expAdd ("gMotorVars[1].Speed_krpm", getQValue(24));
expAdd ("gMotorVars[1].Vd", getQValue(24));
expAdd ("gMotorVars[1].Vq", getQValue(24));
expAdd ("gMotorVars[1].Vs", getQValue(24));
expAdd ("gMotorVars[1].Id_A", getQValue(24));
expAdd ("gMotorVars[1].Iq_A", getQValue(24));
expAdd ("gMotorVars[1].Is_A", getQValue(24));
expAdd ("gMotorVars[1].VdcBus_kV", getQValue(24));
expAdd ("pid[1]", getQValue(24));
expAdd ("gPwmData[1]", getQValue(24));
expAdd ("gDrvSpi8305Vars[1]");
