expRemoveAll();
expAdd ("gMotorVars[0].Flag_enableSys", getDecimal());
expAdd ("gMotorVars[0].Flag_Run_Identify", getDecimal());
expAdd ("gMotorVars[0].Flag_enableOffsetcalc", getDecimal());
expAdd ("gMotorVars[0].Flag_enableAlignment", getDecimal());
expAdd ("gMotorVars[0].SpeedRef_krpm", getQValue(24));
expAdd ("gMotorVars[0].MaxAccel_krpmps", getQValue(24));
expAdd ("gMotorVars[0].MaxJrk_krpmps2", getQValue(20));
expAdd ("gMotorVars[0].Speed_krpm", getQValue(24));
expAdd ("gMotorVars[0].SpinTAC.VelCtlStatus");
expAdd ("gMotorVars[0].SpinTAC.VelCtlBw_radps", getQValue(20));
expAdd ("gMotorVars[0].SpinTAC.VelCtlErrorID");
expAdd ("gMotorVars[0].SpinTAC.VelMoveStatus");
expAdd ("gMotorVars[0].SpinTAC.VelMoveCurveType");
expAdd ("gMotorVars[0].SpinTAC.VelMoveTime_ticks");
expAdd ("gMotorVars[0].SpinTAC.VelMoveErrorID");
expAdd ("gMotorVars[0].Vd", getQValue(24));
expAdd ("gMotorVars[0].Vq", getQValue(24));
expAdd ("gMotorVars[0].Vs", getQValue(24));
expAdd ("gMotorVars[0].Id_A", getQValue(24));
expAdd ("gMotorVars[0].Iq_A", getQValue(24));
expAdd ("gMotorVars[0].Is_A", getQValue(24));
expAdd ("gMotorVars[0].VdcBus_kV", getQValue(24));
expAdd ("pid[0]", getQValue(24));
expAdd ("gPwmData[0]", getQValue(24));
expAdd ("gDrvSpi8301Vars[0]");

expAdd ("gMotorVars[1].Flag_Run_Identify", getDecimal());
expAdd ("gMotorVars[1].Flag_enableOffsetcalc", getDecimal());
expAdd ("gMotorVars[1].Flag_enableAlignment", getDecimal());
expAdd ("gMotorVars[1].SpeedRef_krpm", getQValue(24));
expAdd ("gMotorVars[1].MaxAccel_krpmps", getQValue(24));
expAdd ("gMotorVars[1].MaxJrk_krpmps2", getQValue(20));
expAdd ("gMotorVars[1].Speed_krpm", getQValue(24));
expAdd ("gMotorVars[1].SpinTAC.VelCtlStatus");
expAdd ("gMotorVars[1].SpinTAC.VelCtlBw_radps", getQValue(20));
expAdd ("gMotorVars[1].SpinTAC.VelCtlErrorID");
expAdd ("gMotorVars[1].SpinTAC.VelMoveStatus");
expAdd ("gMotorVars[1].SpinTAC.VelMoveCurveType");
expAdd ("gMotorVars[1].SpinTAC.VelMoveTime_ticks");
expAdd ("gMotorVars[1].SpinTAC.VelMoveErrorID");
expAdd ("gMotorVars[1].Vd", getQValue(24));
expAdd ("gMotorVars[1].Vq", getQValue(24));
expAdd ("gMotorVars[1].Vs", getQValue(24));
expAdd ("gMotorVars[1].Id_A", getQValue(24));
expAdd ("gMotorVars[1].Iq_A", getQValue(24));
expAdd ("gMotorVars[1].Is_A", getQValue(24));
expAdd ("gMotorVars[1].VdcBus_kV", getQValue(24));
expAdd ("pid[1]", getQValue(24));
expAdd ("gPwmData[1]", getQValue(24));
expAdd ("gDrvSpi8301Vars[1]");
